<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\DataVendor;

class DataVendorSeeder extends Seeder
{
    public function run(): void
    {
        $vendors = [
            [
                'nama_vendor' => 'PT Agensi Digital Prima',
                'email_vendor' => 'contact@agensidigitalprima.co.id',
                'nama_pic' => 'Budi Santoso',
                'no_ktp_pic' => '1234567890123456',
                'role_pic' => 'Marketing Manager',
                'email_pic' => 'budi.santoso@agensidigitalprima.co.id',
                'tanggal_registrasi' => '2024-11-01',
                'status' => 'Active',
                'catatan' => 'Vendor untuk campaign digital',
            ],
            [
                'nama_vendor' => 'Social Media Indonesia',
                'email_vendor' => 'info@socialmediaindonesia.com',
                'nama_pic' => 'Siti Nurhaliza',
                'no_ktp_pic' => '2345678901234567',
                'role_pic' => 'Social Media Strategist',
                'email_pic' => 'siti@socialmediaindonesia.com',
                'tanggal_registrasi' => '2024-10-15',
                'status' => 'Active',
                'catatan' => 'Spesialis influencer collaboration',
            ],
            [
                'nama_vendor' => 'Creative Content Lab',
                'email_vendor' => 'hello@creativecontentlab.id',
                'nama_pic' => 'Ahmad Wijaya',
                'no_ktp_pic' => '3456789012345678',
                'role_pic' => 'Creative Director',
                'email_pic' => 'ahmad@creativecontentlab.id',
                'tanggal_registrasi' => '2024-09-20',
                'status' => 'Active',
                'catatan' => 'Produksi konten berkualitas tinggi',
            ],
            [
                'nama_vendor' => 'Analytics Plus',
                'email_vendor' => 'support@analyticsplus.co.id',
                'nama_pic' => 'Rini Wulandari',
                'no_ktp_pic' => '4567890123456789',
                'role_pic' => 'Data Analyst',
                'email_pic' => 'rini@analyticsplus.co.id',
                'tanggal_registrasi' => '2024-08-10',
                'status' => 'Active',
                'catatan' => 'Analisa mendalam campaign performa',
            ],
            [
                'nama_vendor' => 'Media Buying Pro',
                'email_vendor' => 'deals@mediabuyingpro.id',
                'nama_pic' => 'Eko Prasetyo',
                'no_ktp_pic' => '5678901234567890',
                'role_pic' => 'Media Buyer',
                'email_pic' => 'eko@mediabuyingpro.id',
                'tanggal_registrasi' => '2024-07-05',
                'status' => 'Active',
                'catatan' => 'Negoisasi media rate terbaik',
            ],
            [
                'nama_vendor' => 'Influencer Network Asia',
                'email_vendor' => 'contact@influencernetworkasia.com',
                'nama_pic' => 'Devika Patel',
                'no_ktp_pic' => '6789012345678901',
                'role_pic' => 'Influencer Manager',
                'email_pic' => 'devika@influencernetworkasia.com',
                'tanggal_registrasi' => '2024-11-10',
                'status' => 'Pending',
                'catatan' => 'Baru bergabung, dalam proses verifikasi',
            ],
            [
                'nama_vendor' => 'Brand Activation Studio',
                'email_vendor' => 'studio@brandactivation.co.id',
                'nama_pic' => 'Yanto Hermawan',
                'no_ktp_pic' => '7890123456789012',
                'role_pic' => 'Brand Activation Lead',
                'email_pic' => 'yanto@brandactivation.co.id',
                'tanggal_registrasi' => '2024-06-15',
                'status' => 'Active',
                'catatan' => 'Event dan aktivasi brand experience',
            ],
            [
                'nama_vendor' => 'Video Production Masters',
                'email_vendor' => 'productions@videomaster.id',
                'nama_pic' => 'Hendra Sutrisno',
                'no_ktp_pic' => '8901234567890123',
                'role_pic' => 'Production Manager',
                'email_pic' => 'hendra@videomaster.id',
                'tanggal_registrasi' => '2024-05-20',
                'status' => 'Active',
                'catatan' => 'Produksi video berkualitas broadcast',
            ],
            [
                'nama_vendor' => 'Community Management Pro',
                'email_vendor' => 'team@cmgpro.co.id',
                'nama_pic' => 'Lisa Handini',
                'no_ktp_pic' => '9012345678901234',
                'role_pic' => 'Community Manager',
                'email_pic' => 'lisa@cmgpro.co.id',
                'tanggal_registrasi' => '2024-10-01',
                'status' => 'Active',
                'catatan' => 'Manajemen komunitas online 24/7',
            ],
            [
                'nama_vendor' => 'Digital PR Agency',
                'email_vendor' => 'pr@digitalprindo.com',
                'nama_pic' => 'Citra Dewi',
                'no_ktp_pic' => '0123456789012345',
                'role_pic' => 'PR Manager',
                'email_pic' => 'citra@digitalprindo.com',
                'tanggal_registrasi' => '2024-04-12',
                'status' => 'Inactive',
                'catatan' => 'Kurangi aktivitas, sedang hiatus',
            ],
            [
                'nama_vendor' => 'Content SEO Master',
                'email_vendor' => 'seo@contentmaster.id',
                'nama_pic' => 'Bambang Irawan',
                'no_ktp_pic' => '1123456789012345',
                'role_pic' => 'SEO Specialist',
                'email_pic' => 'bambang@contentmaster.id',
                'tanggal_registrasi' => '2024-03-08',
                'status' => 'Active',
                'catatan' => 'Optimasi konten untuk SEO',
            ],
            [
                'nama_vendor' => 'E-commerce Solutions',
                'email_vendor' => 'solutions@ecommerceid.com',
                'nama_pic' => 'Fiona Kusuma',
                'no_ktp_pic' => '2234567890123456',
                'role_pic' => 'E-commerce Manager',
                'email_pic' => 'fiona@ecommerceid.com',
                'tanggal_registrasi' => '2024-09-05',
                'status' => 'Active',
                'catatan' => 'Manajemen toko online dan penjualan',
            ],
            [
                'nama_vendor' => 'Graphics Design Hub',
                'email_vendor' => 'design@graphicshub.id',
                'nama_pic' => 'Rudi Gunawan',
                'no_ktp_pic' => '3345678901234567',
                'role_pic' => 'Design Lead',
                'email_pic' => 'rudi@graphicshub.id',
                'tanggal_registrasi' => '2024-08-22',
                'status' => 'Active',
                'catatan' => 'Desain grafis dan branding visual',
            ],
            [
                'nama_vendor' => 'Email Marketing Experts',
                'email_vendor' => 'campaigns@emailmarketingx.co.id',
                'nama_pic' => 'Winda Serlina',
                'no_ktp_pic' => '4456789012345678',
                'role_pic' => 'Email Campaign Manager',
                'email_pic' => 'winda@emailmarketingx.co.id',
                'tanggal_registrasi' => '2024-07-18',
                'status' => 'Active',
                'catatan' => 'Campaign email marketing terintegrasi',
            ],
            [
                'nama_vendor' => 'Mobile App Developer',
                'email_vendor' => 'dev@mobileappdev.id',
                'nama_pic' => 'Toni Sudarman',
                'no_ktp_pic' => '5567890123456789',
                'role_pic' => 'App Developer',
                'email_pic' => 'toni@mobileappdev.id',
                'tanggal_registrasi' => '2024-06-30',
                'status' => 'Blocked',
                'catatan' => 'Tidak lagi bekerja sama, kontrak terputus',
            ],
            [
                'nama_vendor' => 'Market Research Indonesia',
                'email_vendor' => 'research@marketresearch.co.id',
                'nama_pic' => 'Iris Mulyono',
                'no_ktp_pic' => '6678901234567890',
                'role_pic' => 'Research Manager',
                'email_pic' => 'iris@marketresearch.co.id',
                'tanggal_registrasi' => '2024-11-12',
                'status' => 'Pending',
                'catatan' => 'Menunggu approval dari tim legal',
            ],
            [
                'nama_vendor' => 'Podcast Production Studio',
                'email_vendor' => 'studio@podcastpro.id',
                'nama_pic' => 'Nicky Rahman',
                'no_ktp_pic' => '7789012345678901',
                'role_pic' => 'Studio Manager',
                'email_pic' => 'nicky@podcastpro.id',
                'tanggal_registrasi' => '2024-10-25',
                'status' => 'Active',
                'catatan' => 'Produksi podcast berkualitas premium',
            ],
            [
                'nama_vendor' => 'Event Management Pro',
                'email_vendor' => 'events@eventpro.id',
                'nama_pic' => 'Miki Setiadi',
                'no_ktp_pic' => '8890123456789012',
                'role_pic' => 'Event Coordinator',
                'email_pic' => 'miki@eventpro.id',
                'tanggal_registrasi' => '2024-09-14',
                'status' => 'Active',
                'catatan' => 'Pengelolaan event dan aktivasi merek',
            ],
            [
                'nama_vendor' => 'Translation & Localization',
                'email_vendor' => 'translate@localization.co.id',
                'nama_pic' => 'Lina Budiman',
                'no_ktp_pic' => '9901234567890123',
                'role_pic' => 'Localization Manager',
                'email_pic' => 'lina@localization.co.id',
                'tanggal_registrasi' => '2024-08-03',
                'status' => 'Active',
                'catatan' => 'Penerjemahan dan lokalisasi konten',
            ],
        ];

        DataVendor::insert($vendors);
    }
}
