<?php

namespace Database\Seeders;

use App\Models\DataClient;
use Illuminate\Database\Seeder;

class DataClientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Data dari Google Sheets: Data Leads Beyond Viral - BD Teams
     */
    public function run(): void
    {
        $clients = [
            [
                'nama_brand' => 'Nabati',
                'produk' => 'Richeese, Nextar',
                'category' => 'F&B',
                'priority' => 'P4 - 20%',
                'website' => 'https://www.nabatisnack.co.id/',
                'nama_pic' => 'Bernardus Randyanto',
                'role_pic' => 'Senior Marketing Manager',
                'email_pic' => 'bernardus.randyanto@nabatisnack.co.id',
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => '2024-10-22',
                'notes' => null,
            ],
            [
                'nama_brand' => 'Nabati',
                'produk' => 'Richeese, Nextar',
                'category' => 'F&B',
                'priority' => 'P4 - 20%',
                'website' => 'https://www.nabatisnack.co.id/',
                'nama_pic' => 'Nabila Mauludi',
                'role_pic' => 'Brand Manager',
                'email_pic' => 'nabila.mauludi@nabatisnack.co.id',
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => '2024-10-23',
                'notes' => null,
            ],
            [
                'nama_brand' => 'Nabati',
                'produk' => 'Richeese, Nextar',
                'category' => 'F&B',
                'priority' => 'P4 - 20%',
                'website' => 'https://www.nabatisnack.co.id/',
                'nama_pic' => 'Ihid Itty',
                'role_pic' => 'Brand Manager',
                'email_pic' => 'ihid.itty@nabatisnack.co.id',
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => '2024-10-23',
                'notes' => null,
            ],
            [
                'nama_brand' => 'Garudafood',
                'produk' => 'Tic Tac, Gerry Chocolate, Kacang Garuda',
                'category' => 'F&B',
                'priority' => 'P4 - 20%',
                'website' => 'https://www.garudafood.co.id/',
                'nama_pic' => 'Puspita Ismawati',
                'role_pic' => 'Customer Marketing Brand Manager',
                'email_pic' => 'puspita.ismawati@garudafood.co.id',
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => null,
                'notes' => 'email bounced back',
            ],
            [
                'nama_brand' => 'Garudafood',
                'produk' => 'Tic Tac, Gerry Chocolate, Kacang Garuda',
                'category' => 'F&B',
                'priority' => 'P4 - 20%',
                'website' => 'https://www.garudafood.co.id/',
                'nama_pic' => 'Komarudin',
                'role_pic' => 'Marketing Manager',
                'email_pic' => 'komarudin@garudafood.co.id',
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => null,
                'notes' => 'email bounced back',
            ],
            [
                'nama_brand' => 'Garudafood',
                'produk' => 'Tic Tac, Gerry Chocolate, Kacang Garuda',
                'category' => 'F&B',
                'priority' => 'P4 - 20%',
                'website' => 'https://www.garudafood.co.id/',
                'nama_pic' => 'Rera Hidayat',
                'role_pic' => 'Marketing Manager',
                'email_pic' => 'rera.hidayat@garudafood.co.id',
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => null,
                'notes' => null,
            ],
            [
                'nama_brand' => 'Orang Tua',
                'produk' => 'Tango, Fullo',
                'category' => 'F&B',
                'priority' => 'P4 - 20%',
                'website' => 'https://www.ot.id/',
                'nama_pic' => 'Timothy Jo',
                'role_pic' => 'Digital Marketing Manager',
                'email_pic' => 'timothy.jo@ot.id',
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => '2024-10-27',
                'notes' => null,
            ],
            [
                'nama_brand' => 'Mayora',
                'produk' => 'Le Minerale, Collagen, Riema Kelapa, Reng Reng',
                'category' => 'F&B',
                'priority' => 'P4 - 20%',
                'website' => 'https://www.mayoraindah.co.id/',
                'nama_pic' => 'Charina Nasution',
                'role_pic' => 'Digital Marketing & PR Lead',
                'email_pic' => 'charina.nasution@mayora.co.id',
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => null,
                'notes' => 'email bounced back',
            ],
            [
                'nama_brand' => 'Mayora',
                'produk' => 'Le Minerale, Collagen, Riema Kelapa, Reng Reng',
                'category' => 'F&B',
                'priority' => 'P4 - 20%',
                'website' => 'https://www.mayoraindah.co.id/',
                'nama_pic' => 'Puri Purwaningsih',
                'role_pic' => 'Media, PR & Digital Marketing',
                'email_pic' => 'puri.purwaningsih@mayora.co.id',
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => '2024-10-27',
                'notes' => null,
            ],
            [
                'nama_brand' => 'Paragon',
                'produk' => 'Wardah, Kahf, Emina, etc',
                'category' => 'Beauty',
                'priority' => 'P4 - 20%',
                'website' => 'https://www.paragon-innovation.co.id/',
                'nama_pic' => 'Muhammad Imtaqin',
                'role_pic' => 'Brand Digital Deputy Manager of Kahf',
                'email_pic' => 'muhammad.imtaqin@pti-cosmetics.com',
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => '2024-10-27',
                'notes' => null,
            ],
            [
                'nama_brand' => 'Paragon',
                'produk' => 'Wardah, Kahf, Emina, etc',
                'category' => 'Beauty',
                'priority' => 'P4 - 20%',
                'website' => 'https://www.paragon-innovation.co.id/',
                'nama_pic' => 'Vania Effireswari',
                'role_pic' => 'Digital Ecosystem Deputy',
                'email_pic' => 'vania.effireswari@pti-cosmetics.com',
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => null,
                'notes' => 'email bounced back',
            ],
            [
                'nama_brand' => 'Cimory',
                'produk' => 'Cimory, Kandler',
                'category' => 'F&B',
                'priority' => 'P4 - 20%',
                'website' => 'https://cimory.com/',
                'nama_pic' => 'Olga Wawoh',
                'role_pic' => 'Digital Marketing Supervisor',
                'email_pic' => 'olga.raisa@cimory.com',
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => null,
                'notes' => 'email bounced back',
            ],
            [
                'nama_brand' => 'Cimory',
                'produk' => 'Cimory, Kandler',
                'category' => 'F&B',
                'priority' => 'P4 - 20%',
                'website' => 'https://cimory.com/',
                'nama_pic' => 'Lidwina Tandy',
                'role_pic' => 'Marketing Manager',
                'email_pic' => 'lidwina.tandy@cimory.com',
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => '2024-10-27',
                'notes' => 'on leave',
            ],
            [
                'nama_brand' => 'Jaipra',
                'produk' => 'Seafood',
                'category' => 'F&B',
                'priority' => 'P4 - 20%',
                'website' => 'https://jaipra.com/',
                'nama_pic' => 'Diandra Siwanto',
                'role_pic' => 'Digital Marketing',
                'email_pic' => 'diandra.siwanto@jaipra.com',
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => '2024-10-27',
                'notes' => null,
            ],
            [
                'nama_brand' => 'Jaipra',
                'produk' => 'Seafood',
                'category' => 'F&B',
                'priority' => 'P4 - 20%',
                'website' => 'https://jaipra.com/',
                'nama_pic' => 'Ruslan Fahrudy',
                'role_pic' => 'Marketing Manager',
                'email_pic' => 'ruslan.fahrudy@jaipra.com',
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => '2024-10-28',
                'notes' => null,
            ],
            [
                'nama_brand' => 'Godrej',
                'produk' => 'HIT, Stella',
                'category' => 'Home Care',
                'priority' => 'P4 - 20%',
                'website' => 'https://www.godreindonesia.com/',
                'nama_pic' => '-',
                'role_pic' => null,
                'email_pic' => null,
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => null,
                'notes' => null,
            ],
            [
                'nama_brand' => 'Delfi',
                'produk' => 'Silver Queen',
                'category' => 'F&B',
                'priority' => 'P4 - 20%',
                'website' => 'https://www.delfimarketing.com/',
                'nama_pic' => 'John Wilang',
                'role_pic' => 'Group Product Marketing Manager',
                'email_pic' => 'john.soh@delfimarketing.com',
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => '2024-11-05',
                'notes' => null,
            ],
            [
                'nama_brand' => 'Nutrifood',
                'produk' => 'Tropicana Slim, L-Men, Fibar',
                'category' => 'F&B',
                'priority' => 'P4 - 20%',
                'website' => 'https://www.nutrifood.co.id/',
                'nama_pic' => 'Fransiska Hadiman',
                'role_pic' => 'Head of Media and Digital Business',
                'email_pic' => 'elvina@nutrifood.co.id',
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => '2024-11-06',
                'notes' => null,
            ],
            [
                'nama_brand' => 'Nutrifood',
                'produk' => 'Tropicana Slim, L-Men, Fibar',
                'category' => 'F&B',
                'priority' => 'P4 - 20%',
                'website' => 'https://www.nutrifood.co.id/',
                'nama_pic' => 'Hendi Herdianiyah',
                'role_pic' => 'Media & Digital Marketing Specialist',
                'email_pic' => 'hendi.herdianiyah@nutrifood.co.id',
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => '2024-11-06',
                'notes' => null,
            ],
            [
                'nama_brand' => 'Ultrajaya',
                'produk' => 'Ultra Milk',
                'category' => 'F&B',
                'priority' => 'P4 - 20%',
                'website' => 'https://www.ultrajaya.co.id/',
                'nama_pic' => 'Resti Herdirayani',
                'role_pic' => 'F&B Marketing Manager',
                'email_pic' => 'resti.herdirayani@ultrajaya.co.id',
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => '2024-10-16',
                'notes' => null,
            ],
            [
                'nama_brand' => 'Ultrajaya',
                'produk' => 'Ultra Milk',
                'category' => 'F&B',
                'priority' => 'P4 - 20%',
                'website' => 'https://www.ultrajaya.co.id/',
                'nama_pic' => 'Radiyo Egyllandora',
                'role_pic' => 'Brand Manager Ultra Milk & Teh Kotak',
                'email_pic' => 'radiyo.egyllandora@ultrajaya.co.id',
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => null,
                'notes' => null,
            ],
            [
                'nama_brand' => 'Greenfields',
                'produk' => null,
                'category' => 'F&B',
                'priority' => 'P4 - 20%',
                'website' => 'https://greenfielddairy.com/',
                'nama_pic' => 'Adi Reformawardhani',
                'role_pic' => 'Digital & CRM Executive',
                'email_pic' => 'adi.reformawardhani@greenfielddairy.com',
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => null,
                'notes' => null,
            ],
            [
                'nama_brand' => 'Greenfields',
                'produk' => null,
                'category' => 'F&B',
                'priority' => 'P4 - 20%',
                'website' => 'https://greenfielddairy.com/',
                'nama_pic' => 'Kesia Gabriela',
                'role_pic' => 'Media & Digital Manager',
                'email_pic' => 'kesia.lakat@greenfielddairy.com',
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => null,
                'notes' => null,
            ],
            [
                'nama_brand' => 'CooVita',
                'produk' => null,
                'category' => 'F&B',
                'priority' => 'P4 - 20%',
                'website' => 'https://coolvita.co.id/',
                'nama_pic' => 'Dian Fitrdhawati',
                'role_pic' => 'Head of Media and Digital Marketing Management',
                'email_pic' => '-',
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => null,
                'notes' => null,
            ],
            [
                'nama_brand' => 'CooVita',
                'produk' => null,
                'category' => 'F&B',
                'priority' => 'P4 - 20%',
                'website' => 'https://coolvita.co.id/',
                'nama_pic' => 'Deotha Tiatra',
                'role_pic' => 'Senior Content Specialist',
                'email_pic' => null,
                'status' => 'Sent',
                'date_outreach' => '2024-10-16',
                'date_follow_up' => null,
                'notes' => null,
            ],
        ];

        foreach ($clients as $client) {
            DataClient::create($client);
        }
    }
}
